"use strict";

const fs = require("fs");
const path = require("path");


const ROOT = path.join(__dirname, "..");


const PURPOSE_FILE =
    path.join(ROOT, "purposes.js");


const CATEGORY_FILE =
    path.join(ROOT, "categories.js");


const OUTPUT_FILE =
    path.join(ROOT, "generated", "topics.js");


const PROGRESS_FILE =
    path.join(ROOT, "generated", "topics-progress.json");


const GROQ_API_KEY =
    process.env.GROQ_API_KEY;





function sleep(ms) {

    return new Promise(
        resolve => setTimeout(resolve, ms)
    );

}







function loadArrayFromJS(filePath, variableName) {


    const content =
        fs.readFileSync(
            filePath,
            "utf8"
        );


    const start =
        content.indexOf(
            `const ${variableName}`
        );


    if (start === -1) {

        throw new Error(
            `${variableName} not found`
        );

    }



    const arrayStart =
        content.indexOf(
            "[",
            start
        );


    let depth = 0;

    let arrayEnd = -1;



    for (
        let i = arrayStart;
        i < content.length;
        i++
    ) {


        if (content[i] === "[") {

            depth++;

        }


        else if (content[i] === "]") {


            depth--;


            if (depth === 0) {

                arrayEnd = i;
                break;

            }

        }

    }



    if (arrayEnd === -1) {

        throw new Error(
            `Unable to read ${variableName}`
        );

    }



    const arrayText =
        content.substring(
            arrayStart,
            arrayEnd + 1
        );



    return eval(arrayText);

}







function getPurposes() {

    return loadArrayFromJS(
        PURPOSE_FILE,
        "VW_PURPOSES"
    );

}







function getCategories() {

    return loadArrayFromJS(
        CATEGORY_FILE,
        "VW_CATEGORIES"
    );

}









async function generateWithGroq(category) {


    const prompt = `

You are a global LinkedIn content strategist.

Generate LinkedIn post topics.


Purpose:
${category.purpose}


Category:
${category.label}


Description:
${category.description}



Generate exactly 20 topics.


Rules:

- Global audience
- Professional LinkedIn quality
- Useful and actionable
- No duplicate ideas
- No hashtags
- No emojis
- Avoid generic topics


Return ONLY JSON.


Format:

[
 {
  "id":"short-kebab-case-id",
  "label":"Topic Name",
  "category":"${category.id}",
  "description":"Short explanation"
 }
]

`;




    let attempts = 0;



    while(attempts < 10) {


        attempts++;



        const response =
            await fetch(
                "https://api.groq.com/openai/v1/chat/completions",
                {

                    method:"POST",


                    headers:{

                        "Authorization":
                        `Bearer ${GROQ_API_KEY}`,

                        "Content-Type":
                        "application/json"

                    },


                    body:JSON.stringify({

                        model:
                        "llama-3.3-70b-versatile",


                        temperature:
                        0.2,


                        messages:[

                            {
                                role:"user",
                                content:prompt
                            }

                        ]

                    })

                }
            );



        const data =
            await response.json();




        if(response.ok && data.choices){


            let text =
                data.choices[0]
                .message
                .content;



            text =
                text
                .replace(/```json/g,"")
                .replace(/```/g,"")
                .trim();



            return JSON.parse(text);

        }






        if(
            data.error &&
            data.error.code === "rate_limit_exceeded"
        ){


            console.log(
                "Groq limit reached. Waiting 60 seconds..."
            );


            await sleep(60000);


            continue;

        }




        console.log(data);


        throw new Error(
            "Groq API failed"
        );


    }



    throw new Error(
        "Groq failed after retries"
    );

}









function saveProgress(topics) {


    fs.mkdirSync(
        path.dirname(PROGRESS_FILE),
        {
            recursive:true
        }
    );



    fs.writeFileSync(

        PROGRESS_FILE,

        JSON.stringify(
            topics,
            null,
            4
        )

    );

}









function createFinalTopics(topics) {


    const output =

`"use strict";

/* ==========================================================================
   VIDHWAAN AI Writer

   Generated Topic Library

   Auto Generated By GitHub Actions + Groq AI

   Flow:

   Purpose → Category → Topic
   ========================================================================== */


const VW_TOPICS = Object.freeze(

${JSON.stringify(topics,null,4)}

);


Object.freeze(VW_TOPICS);
`;



    fs.writeFileSync(
        OUTPUT_FILE,
        output
    );

}









async function generateTopics() {


    if(!GROQ_API_KEY){

        throw new Error(
            "GROQ_API_KEY missing"
        );

    }




    const purposes =
        getPurposes();



    const categories =
        getCategories();





    console.log(
        "Purposes:",
        purposes.length
    );



    console.log(
        "Categories:",
        categories.length
    );





    let topics = [];




    if(
        fs.existsSync(
            PROGRESS_FILE
        )
    ){


        topics =
            JSON.parse(
                fs.readFileSync(
                    PROGRESS_FILE,
                    "utf8"
                )
            );


        console.log(
            "Resuming:",
            topics.length,
            "topics already generated"
        );


    }






    for(
        let i=0;
        i<categories.length;
        i++
    ){



        const category =
            categories[i];




        const exists =
            topics.some(
                t =>
                t.category === category.id
            );



        if(exists){


            console.log(
                "Skipping:",
                category.label
            );


            continue;

        }






        console.log(

            `[${i+1}/${categories.length}]`,
            category.purpose,
            "→",
            category.label

        );






        const result =
            await generateWithGroq(
                category
            );




        topics.push(
            ...result
        );



        saveProgress(
            topics
        );



        console.log(
            "Saved:",
            topics.length,
            "topics"
        );




        await sleep(30000);


    }





    createFinalTopics(
        topics
    );



    console.log(
        "Completed:",
        topics.length,
        "topics"
    );

}









function validateTopics(){



    if(
        !fs.existsSync(
            OUTPUT_FILE
        )
    ){

        throw new Error(
            "topics.js missing"
        );

    }



    const content =
        fs.readFileSync(
            OUTPUT_FILE,
            "utf8"
        );



    if(
        !content.includes(
            "VW_TOPICS"
        )
    ){

        throw new Error(
            "Invalid topics.js"
        );

    }



    console.log(
        "Validation successful"
    );

}








if(
    process.argv.includes("--validate")
){

    validateTopics();

}
else{

    generateTopics();

}
