"use strict";

const fs = require("fs");
const path = require("path");


const ROOT = path.join(__dirname, "..");

const PURPOSE_FILE = path.join(ROOT, "purposes.js");
const CATEGORY_FILE = path.join(ROOT, "categories.js");

const OUTPUT_FILE =
    path.join(ROOT, "generated", "topics.js");


const GROQ_API_KEY = process.env.GROQ_API_KEY;



function loadArrayFromJS(filePath, variableName) {

    const content = fs.readFileSync(filePath, "utf8");


    const start =
        content.indexOf(`const ${variableName}`);


    if (start === -1) {
        throw new Error(
            `${variableName} not found in ${filePath}`
        );
    }


    const arrayStart =
        content.indexOf("[", start);


    const arrayEnd =
        content.indexOf("]);", arrayStart);


    if (arrayStart === -1 || arrayEnd === -1) {
        throw new Error(
            `Cannot extract ${variableName}`
        );
    }


    const arrayText =
        content.substring(
            arrayStart,
            arrayEnd + 1
        );


    return eval(arrayText);
}



function getCategories() {

    return loadArrayFromJS(
        CATEGORY_FILE,
        "VW_CATEGORIES"
    );

}



function getPurposes() {

    return loadArrayFromJS(
        PURPOSE_FILE,
        "VW_PURPOSES"
    );

}




async function generateWithGroq(category) {


    const prompt = `

You are a global LinkedIn content strategist.

Generate professional LinkedIn post topics.

Purpose:
${category.purpose}

Category:
${category.label}


Create exactly 30 unique topics.

Rules:

- Global audience
- Professional quality
- Suitable for LinkedIn
- No hashtags
- No emojis
- No duplicate ideas
- Do not create generic topics


Return ONLY JSON.

Format:

[
 {
  "id":"",
  "label":"",
  "category":"${category.id}",
  "description":""
 }
]

`;



    const response =
        await fetch(
            "https://api.groq.com/openai/v1/chat/completions",
            {

                method: "POST",

                headers: {

                    "Authorization":
                    `Bearer ${GROQ_API_KEY}`,

                    "Content-Type":
                    "application/json"

                },


                body: JSON.stringify({

                    model:
                    "llama-3.3-70b-versatile",

                    temperature:
                    0.4,

                    messages: [

                        {
                            role:"user",
                            content:prompt
                        }

                    ]

                })

            });



    const data =
        await response.json();



    let output =
        data.choices[0]
        .message
        .content;


    output =
        output
        .replace(/```json/g,"")
        .replace(/```/g,"")
        .trim();


    return JSON.parse(output);

}




async function generateTopics() {


    if (!GROQ_API_KEY) {

        throw new Error(
            "GROQ_API_KEY missing"
        );

    }



    const purposes =
        getPurposes();


    const categories =
        getCategories();



    console.log(
        "Purposes:",
        purposes.length
    );


    console.log(
        "Categories:",
        categories.length
    );



    let topics = [];



    for (const category of categories) {


        console.log(
            "Generating:",
            category.purpose,
            "→",
            category.label
        );



        const result =
            await generateWithGroq(category);



        topics.push(
            ...result
        );


    }



    fs.mkdirSync(
        path.dirname(OUTPUT_FILE),
        {
            recursive:true
        }
    );



    const fileContent =

`"use strict";

/* ==========================================================================
   VIDHWAAN AI Writer

   Auto Generated Topics
   Generated by GitHub Actions + Groq AI
   ========================================================================== */


const VW_TOPICS = Object.freeze(
${JSON.stringify(topics,null,4)}
);


Object.freeze(VW_TOPICS);
`;



    fs.writeFileSync(
        OUTPUT_FILE,
        fileContent
    );



    console.log(
        "Created",
        topics.length,
        "topics"
    );

}




function validate() {


    if (!fs.existsSync(OUTPUT_FILE)) {

        throw new Error(
            "topics.js not found"
        );

    }


    const content =
        fs.readFileSync(
            OUTPUT_FILE,
            "utf8"
        );


    if (!content.includes("VW_TOPICS")) {

        throw new Error(
            "Invalid topics.js"
        );

    }


    console.log(
        "Validation successful"
    );

}





if (
    process.argv.includes("--validate")
) {

    validate();

}
else {

    generateTopics();

}
