"use strict";

/* ==========================================================================
   VIDHWAAN AI Writer

   Topic Generator
   CI/CD Automation

   Reads:
   data/categories.js

   Creates:
   data/topics.js

   ========================================================================== */


const fs = require("fs");
const path = require("path");



const GROQ_API =

"https://api.groq.com/openai/v1/chat/completions";



const MODEL =

"llama-3.3-70b-versatile";





async function main(){


    const apiKey =

    process.env.GROQ_API_KEY;



    if(!apiKey){

        throw new Error(
            "GROQ_API_KEY missing"
        );

    }




    const categoriesPath =

    path.join(

        process.cwd(),

        "data",

        "categories.js"

    );



    const categoriesText =

    fs.readFileSync(

        categoriesPath,

        "utf8"

    );





    const prompt = `

You are generating a professional topic library for VIDHWAAN AI Writer.

Analyze these categories:

${categoriesText}


Generate topics for every category.

Rules:

- Every category must have 10 to 15 topics.
- Topics must be globally useful.
- Avoid duplicates.
- Avoid narrow local topics.
- Use professional wording.
- Include a short description.

Return ONLY valid JSON.

Format:

[
 {
  "id":"topic-id",
  "label":"Topic Name",
  "category":"category-id",
  "description":"Short description"
 }
]

`;





    const response =

    await fetch(

        GROQ_API,

        {

            method:"POST",

            headers:{

                "Authorization":

                `Bearer ${apiKey}`,

                "Content-Type":

                "application/json"

            },


            body:JSON.stringify({

                model:MODEL,


                messages:[

                    {

                        role:"user",

                        content:prompt

                    }

                ],


                temperature:0.3,


                response_format:{

                    type:"json_object"

                }


            })


        }

    );






    if(!response.ok){


        throw new Error(

            await response.text()

        );


    }






    const result =

    await response.json();





    const content =

    result

    .choices[0]

    .message

    .content;





    const parsed =

    JSON.parse(content);





    const topics =

    Array.isArray(parsed)

    ? parsed

    : parsed.topics;






    if(!topics || !topics.length){

        throw new Error(
            "No topics generated"
        );

    }





    validate(topics);





    const output = `

"use strict";

/* ==========================================================================
   VIDHWAAN AI Writer

   Generated Topic Library

   Automatically generated by CI/CD

   ========================================================================== */


const VW_TOPICS = Object.freeze(${JSON.stringify(
    topics,
    null,
    4
)});


export default VW_TOPICS;

`;






    const outputPath =

    path.join(

        process.cwd(),

        "data",

        "topics.js"

    );




    fs.writeFileSync(

        outputPath,

        output

    );



    console.log(

        "Topics generated:",

        topics.length

    );


}







function validate(topics){


    for(const topic of topics){


        if(

            !topic.id ||

            !topic.label ||

            !topic.category

        ){

            throw new Error(

                "Invalid topic format"

            );

        }


    }


}






main()

.catch(

error=>{

console.error(error);

process.exit(1);

}

);
